# Generated by Django 2.2.3 on 2019-07-10 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('year', models.SmallIntegerField()),
                ('director_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('assigned_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Code')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
