# Generated by Django 2.2.3 on 2019-08-02 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190713_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=50)),
                ('third_name', models.CharField(max_length=50)),
                ('passport_lot', models.CharField(max_length=3)),
                ('passport_number', models.CharField(max_length=8)),
                ('gender', models.CharField(max_length=1)),
                ('assigned_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Classes')),
            ],
        ),
    ]
