# Generated by Django 2.2.3 on 2019-08-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='passport_lot',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='passport_number',
            field=models.BinaryField(),
        ),
    ]
