# Generated by Django 2.2.3 on 2019-12-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190810_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='passport_lot',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='students',
            name='passport_number',
            field=models.CharField(max_length=10),
        ),
    ]
